case erlang:system_info(otp_release) of
    [$R|_] = Vsn when Vsn < "R16" ->
        CONFIG;
    _ ->
        HashDefine = [{d,new_hash}],
        case lists:keysearch(erl_opts, 1, CONFIG) of
            {value, {erl_opts, Opts}} ->
                lists:keyreplace(erl_opts,1,CONFIG,{erl_opts,Opts++HashDefine});
            false ->
                CONFIG ++ [{erl_opts, HashDefine}]
        end
end.
